### ISSUE TITLE
bug: production site nextauth (google) returns 500 error and does not authenticate

### ISSUE THREAD

**Issue by joshgamache** [button-inc/emissions-elt-demo#226]
### 🐛 Description of the bug

While the build is passing, there displayed page does not allow for auth to complete. The issue seems related to Next Auth (and maybe Docker variables?), but more research is needed. 

### To reproduce
1. Navigate to [production site](http://http://34.125.36.177/)

**Actual outcome**: The page displays, but with non-functional auth buttons.

Console log: 
```console
-> POST HTTP://34.125.36.177/api/auth/signin/google? 500 (Internal Server Error)
```

**Expected outcome**: Site Auth page should have a functional Google auth button.

**Comment by YaokunLin** [comment]
![image](https://user-images.githubusercontent.com/72329369/230974608-f4edd67b-d452-4a3a-ad63-87a9d292b813.png)

**Comment by shon-button** [comment]
For [production site](http://http//34.125.36.177/) issue:  "POST HTTP://34.125.36.177/api/auth/signin/google? 500 (Internal Server Error)"

Are the values set for the following variables:
GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET

**Comment by YaokunLin** [comment]
based on the GKE log I found based on the pod that is running, the issue seems come from the `window` object? Plz take a look @joshgamache  @shon-button , the logs did not complain that it could not find the newly added env variables
![image](https://user-images.githubusercontent.com/72329369/231517993-032a07fc-16cb-4ecc-99c1-ae510ada231d.png)
![image](https://user-images.githubusercontent.com/72329369/231518136-0f1cedc9-8458-4e85-9473-8d3bd81e9288.png)

**Comment by joshgamache** [comment]
@shon-button Those values are set in the [GCP Secrets manager](https://console.cloud.google.com/security/secret-manager?project=emissions-elt-demo), which get passed in through the build (see [~/cloudbuild.yaml:53-69 & 97-100](https://github.com/button-inc/emissions-elt-demo/blob/e54fa00fc09473f9ad0b1778e6c5998883fd8095/cloudbuild.yaml#L53), which pass to docker as args and are used in [~/app/Dockerfile:31-39](https://github.com/button-inc/emissions-elt-demo/blob/e54fa00fc09473f9ad0b1778e6c5998883fd8095/app/Dockerfile#L31).

@YaokunLin Curious. It must be because of something about it running in Docker. Locally, everything is running in the browser, but when it's in prod, it's server side. But it should still expose properly. Might need to change that over to a variable based on dev/local/prod. Not sure if that's what's giving us the auth issue, but still worth correcting.

**Comment by shon-button** [comment]
Perhaps a typo?  In ClimateTrax code base the env vars are:
        "GOOGLE_CLIENT_ID",
        "GOOGLE_CLIENT_SECRET",
But, the cloudbuild.yaml has:
        "NEXTAUTH_GOOGLE_CLIENT_ID",
        "NEXTAUTH_GOOGLE_CLIENT_SECRET",

**Comment by joshgamache** [comment]
I set the variables as different names (which I thought added clarity as to where they're from/used, but I see now does the opposite) passed in the yaml `--build-arg NA_GOOGLE_ID=$$NEXTAUTH_GOOGLE_CLIENT_ID` which changes in the docker file to `ENV GOOGLE_CLIENT_ID=$NA_GOOGLE_ID`. 
That is Google Secret (`NEXTAUTH_GOOGLE_CLIENT_***`) ▶️ Cloud Build (`NA_GOOGLE_***`) ▶️ Dockerfile exposes ENV (`GOOGLE_CLIENT_***`). 

I've tested locally with a built Docker, and it does directly expose the env variables consistent with what happens in GCP.

**Comment by shon-button** [comment]
Has NEXTAUTH_URL environment variable been set to the canonical URL of our prod site?

**Comment by joshgamache** [comment]
## Fix R&D

- All env variables had to be passed along to the Docker image. 
	- This included the secrets used to connect to the DB

### Discovery of Errors: 
1. Clicking a signin partner had no effect.
2. Clicking a signin partner worked, allowed for the auth but then led to a 404.
	1. 
![image](https://user-images.githubusercontent.com/11062580/233409607-c32f756a-9ee2-4851-80e8-fe413596a60c.png)

	2. `error=Callback` was occurring down the line, but triggered as a result of the `api/auth/github` call.
	3. `/api/auth/role` was returning a `500` error, but that error wasn't reflected in the waterfall. The callback error is all that was displayed. `api/auth/role` is called by the `jwt` callback in next auth to verify a user's role.
	4. Needed to pass env variables to Docker so they would be exposed when the api was queried (Postgraphile queries against the Postgres DB but needed permissions).
3. `404` on the auth pages is often due to some kind of error state (like the above, or a user not being found in our DB) but no error page existing in NextAuth. 
4. Google auth doesn't like IPs and [will only work with a TLD.](https://github.com/google/guava/wiki/InternetDomainNameExplained#public-suffixes-and-private-domains)

**Comment by joshgamache** [comment]
If anyone needs to test a particular commit and run it through cloud build, see the below video for a quick how-to-do. Note: This _does deploy it to production!_ Longer term, it might be useful to have another trigger, which would build toward a staging environment.
 
[msedge_NpX0vfBxKM-output.webm](https://user-images.githubusercontent.com/11062580/233490820-edaf81bd-a3e7-4edd-9d6f-17ec85fe6a79.webm)

**Comment by YaokunLin** [comment]
thanks for sharing this video! @joshgamache This cloud build trigger is good to know! I have the same concerns as you that this goes straight to prod then it goes live right after, I feel the best way to test the GKE build is to do it locally with skafold, otherwise it hits prod every time we test it especially for a new guy like me
